---
- name: install lamp stack 
  hosts: firewall
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "install apache2"
      package: name=httpd state=present
    - name: "install php-cli"
      package: name=php-cli state=present
    - name: "install php-mcrypt"
      package: name=php-mcrypt state=present
     - name: "install php-gd"
      package: name=php-gd state=present
    - name: "install php-mysql"
      package: name=php-cli state=present
    - name: "install mysqlserver"
      package: name=mysql-server state=present

