---
 - name: ping Test playbook
   hosts: linux
   vars:
      S: HELLO!
   tasks:
    - name: VSANSibe
      debug:
        msg: "{{ S }}"
    - name: Add or modify ansible.example.org A to 192.168.1.1"
      nsupdate:
        key_name: "nsupdate"
        key_secret: "+bFQtBCta7j2vWkjPkAFtgA=="
        server: "10.1.1.1"
        zone: "local"
        record: "ansible"
        value: "192.168.1.1"
...
